language: node_js

node_js:
  - '5.1.0'

install:
  - npm install
  - ./node_modules/.bin/mozilla-download /tmp/firefox/ --product firefox --branch mozilla-central
  - export FIREFOX_NIGHTLY_BIN="/tmp/firefox/firefox/firefox-bin"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - $CI_ACTION

env:
  global:
    - TEST_SUITE=unit
  matrix:
    - CI_ACTION="npm run test-lint"
    - CI_ACTION="npm run test-unit"

